In [1]:
import numpy as np
#import sys
#sys.path.append('/Users/shuojia/CSV/lhapdf/build/lib/python3.8/site-packages')
import lhapdf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
p_cteq6 = lhapdf.mkPDF("cteq6l1", 0)
p_cteq18 = lhapdf.mkPDF("CT18qed",0)
PDF = p_cteq18

LHAPDF 6.5.0 loading /opt/homebrew/Caskroom/miniconda/base/share/LHAPDF/cteq6l1/cteq6l1_0000.dat
cteq6l1 PDF set, member #0, version 4; LHAPDF ID = 10042
LHAPDF 6.5.0 loading /opt/homebrew/Caskroom/miniconda/base/share/LHAPDF/CT18qed/CT18qed_0000.dat
CT18qed PDF set, member #0, version 1


In [3]:
Hem_file = pd.read_csv('mult_ratio_to_solve_for_F1F2F3.txt',delim_whitespace=True)
Hem_file.head()

#x     Q2      Q      z  h2p_div_d2p_measured  h2p_div_d2p_err  \
0  0.348  3.986  1.996  0.375                1.1144           0.0188   
1  0.348  3.986  1.996  0.425                1.1554           0.0171   
2  0.348  3.986  1.996  0.475                1.1656           0.0214   
3  0.348  3.986  1.996  0.525                1.1152           0.0205   
4  0.348  3.986  1.996  0.575                1.0883           0.0197   

   h2n_div_d2p_measured  h2n_div_d2p_err  d2n_div_d2p_measured  \
0                0.6151           0.0147                0.6924   
1                0.5872           0.0119                0.6709   
2                0.5775           0.0137                0.6574   
3                0.5257           0.0121                0.6383   
4                0.5213           0.0118                0.5770   

   d2n_div_d2p_err  kin    W    F1    F2    F3  
0           0.0165    4  2.9  3.25  1.81  1.13  
1           0.0136    4  2.9  3.40  1.97  1.14  
2           0.0155    4  2.9  3.46  2.02  1.14  
3           0.0142    4  2.9  3.80  2.12  1.21  
4           0.0132    4  2.9  3.83  2.09  1.11

In [4]:
#the equation is 
#A00*F1+A01*F2+A02*F3=B0
#A10*F1+A11*F2+A12*F3=B1
#A20*F1+A21*F2+A22*F3=B2


In [5]:
def Get_R(xbj,Q,z):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    R=5*(u+d+ub+db)/(4*(u+ub)+(d+db))
    return R

In [6]:
def A_00(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    return 4*r1m*(u+d)-4*Get_R(xbj,Q,z)*u
def A_01(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return r1m*(ub+db)-Get_R(xbj,Q,z)*db
def A_02(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return 4*r1m*(ub+db)-4*Get_R(xbj,Q,z)*ub
def B_0(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return Get_R(xbj,Q,z)*d-r1m*(u+d)
    

In [7]:
def A_10(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return (4*r2m*(u+d) - 4*Get_R(xbj,Q,z)*ub)
def A_11(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return r2m*(ub+db)-Get_R(xbj,Q,z)*d
def A_12(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return 4*r2m*(ub+db)-4*Get_R(xbj,Q,z)*u
def B_1(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return Get_R(xbj,Q,z)*db-r2m*(u+d)
    

In [8]:
def A_20(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return (4*r3m*(u+d) - 4*(ub+db))
def A_21(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return r3m*(ub+db)-(u+d)
def A_22(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return 4*r3m*(ub+db)-4*(u+d)
def B_2(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return (ub+db)-r3m*(u+d)
    

In [9]:
for i,row in Hem_file.iterrows():    
    xbj=row['#x']
    z=row['z']
    Q=row['Q']
    r1m=row['h2p_div_d2p_measured']
    r2m=row['h2n_div_d2p_measured']
    r3m=row['d2n_div_d2p_measured']
    A = np.array([[A_00(xbj,Q,z,r1m),A_01(xbj,Q,z,r1m),A_02(xbj,Q,z,r1m)],[A_10(xbj,Q,z,r2m),A_11(xbj,Q,z,r2m),A_12(xbj,Q,z,r2m)],[A_20(xbj,Q,z,r3m),A_21(xbj,Q,z,r3m),A_22(xbj,Q,z,r3m)]])
    B = np.array([B_0(xbj,Q,z,r1m),B_1(xbj,Q,z,r2m),B_2(xbj,Q,z,r3m)])
    F = np.linalg.solve(A,B)
    print(F)

[5.81250621 5.8364489  2.6469798 ]
[-15.07092734 -14.49155738  -6.08410947]
[-8.25258016 -7.55024998 -3.24159983]
[5.77686818 6.72595415 2.06198392]
[2.87624679 2.30943687 1.16616857]
[3.56118717 2.92484663 1.40809007]
[2.96142202 2.10945906 1.05872169]
[-1.87230888 -0.75594735 -0.55754388]
[-2.53324135 -2.16872448 -0.54415232]
[1.18526492 1.30880188 0.6066329 ]
[2.6330272  2.7414588  1.15997228]
[10.26831825 10.17184648  4.31558504]
[387.02381646 361.67385443 145.70551057]
[9.90247583 7.76520078 3.79761763]
[-3.22824779 -2.74202727 -0.99107006]
[-1.84108892 -1.40077256 -0.4676236 ]
[-2.05843469 -2.0208705  -0.44757695]
[3.43004322 3.67519271 1.61765271]
[-5.19354669 -4.47047813 -2.1041055 ]
[-7.36895588 -6.45615568 -3.12532741]
[9.06806653 7.83933891 3.51535482]
[-2.68066735 -2.04063115 -0.91511336]
[-1.90383363 -1.73831085 -0.51990404]
[-1.55479152 -1.44016005 -0.36916545]
[19.77966659 18.98770861  5.16177101]
[-15.54871634 -15.23263889  -7.74137194]
[-7.34751326 -8.30166563 -2.92809