In [1]:
import numpy as np
#import sys
#sys.path.append('/Users/shuojia/CSV/lhapdf/build/lib/python3.8/site-packages')
import lhapdf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
p_cteq6 = lhapdf.mkPDF("cteq6l1", 0)
p_cteq18 = lhapdf.mkPDF("CT18qed",0)
PDF = p_cteq6

LHAPDF 6.5.0 loading /opt/homebrew/Caskroom/miniconda/base/share/LHAPDF/cteq6l1/cteq6l1_0000.dat
cteq6l1 PDF set, member #0, version 4; LHAPDF ID = 10042
LHAPDF 6.5.0 loading /opt/homebrew/Caskroom/miniconda/base/share/LHAPDF/CT18qed/CT18qed_0000.dat
CT18qed PDF set, member #0, version 1


In [3]:
Hem_file = pd.read_csv('mult_ratio_to_solve_for_F1F2F3.txt',delim_whitespace=True)
Hem_file.head()

#x     Q2      Q      z  h2p_div_d2p_measured  h2p_div_d2p_err  \
0  0.348  3.986  1.996  0.375                1.1144           0.0188   
1  0.348  3.986  1.996  0.425                1.1554           0.0171   
2  0.348  3.986  1.996  0.475                1.1656           0.0214   
3  0.348  3.986  1.996  0.525                1.1152           0.0205   
4  0.348  3.986  1.996  0.575                1.0883           0.0197   

   h2n_div_d2p_measured  h2n_div_d2p_err  d2n_div_d2p_measured  \
0                0.6151           0.0147                0.6924   
1                0.5872           0.0119                0.6709   
2                0.5775           0.0137                0.6574   
3                0.5257           0.0121                0.6383   
4                0.5213           0.0118                0.5770   

   d2n_div_d2p_err  kin    W    F1    F2    F3  
0           0.0165    4  2.9  3.25  1.81  1.13  
1           0.0136    4  2.9  3.40  1.97  1.14  
2           0.0155    4  2.9  3.46  2.02  1.14  
3           0.0142    4  2.9  3.80  2.12  1.21  
4           0.0132    4  2.9  3.83  2.09  1.11

In [4]:
#the equation is 
#A00*F1+A01*F2+A02*F3=B0
#A10*F1+A11*F2+A12*F3=B1
#A20*F1+A21*F2+A22*F3=B2


In [5]:
def Get_R(xbj,Q,z):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    R=5*(u+d+ub+db)/(4*(u+ub)+(d+db))
    return R

In [6]:
def A_00(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    return 4*r1m*(u+d)-4*Get_R(xbj,Q,z)*u
def A_01(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return r1m*(ub+db)-Get_R(xbj,Q,z)*db
def A_02(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return 4*r1m*(ub+db)-4*Get_R(xbj,Q,z)*ub
def B_0(xbj,Q,z,r1m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return Get_R(xbj,Q,z)*d-r1m*(u+d)
    

In [7]:
def A_10(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return (4*r2m*(u+d) - 4*Get_R(xbj,Q,z)*ub)
def A_11(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return r2m*(ub+db)-Get_R(xbj,Q,z)*d
def A_12(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return 4*r2m*(ub+db)-4*Get_R(xbj,Q,z)*u
def B_1(xbj,Q,z,r2m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return Get_R(xbj,Q,z)*db-r2m*(u+d)
    

In [8]:
def A_20(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return (4*r3m*(u+d) - 4*(ub+db))
def A_21(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return r3m*(ub+db)-(u+d)
def A_22(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return 4*r3m*(ub+db)-4*(u+d)
def B_2(xbj,Q,z,r3m):
    u=PDF.xfxQ(2,xbj,Q)
    d=PDF.xfxQ(1,xbj,Q)
    ub=PDF.xfxQ(-2,xbj,Q)
    db=PDF.xfxQ(-1,xbj,Q)
    return (ub+db)-r3m*(u+d)
    

In [9]:
for i,row in Hem_file.iterrows():    
    xbj=row['#x']
    z=row['z']
    Q=row['Q']
    r1m=row['h2p_div_d2p_measured']
    r2m=row['h2n_div_d2p_measured']
    r3m=row['d2n_div_d2p_measured']
    A = np.array([[A_00(xbj,Q,z,r1m),A_01(xbj,Q,z,r1m),A_02(xbj,Q,z,r1m)],[A_10(xbj,Q,z,r2m),A_11(xbj,Q,z,r2m),A_12(xbj,Q,z,r2m)],[A_20(xbj,Q,z,r3m),A_21(xbj,Q,z,r3m),A_22(xbj,Q,z,r3m)]])
    B = np.array([B_0(xbj,Q,z,r1m),B_1(xbj,Q,z,r2m),B_2(xbj,Q,z,r3m)])
    F = np.linalg.solve(A,B)
    print(F)

[7.22890223 7.294829   3.1906025 ]
[-9.20669797 -8.87622192 -3.58261308]
[-6.05848674 -5.54564247 -2.29329423]
[7.07216999 8.33441693 2.40769402]
[3.08391476 2.46887248 1.21317818]
[3.93112217 3.22230355 1.50528415]
[3.17143445 2.24117698 1.0969382 ]
[-1.70584261 -0.65760747 -0.49108139]
[-2.25882578 -1.93406694 -0.45268724]
[1.20006236 1.33751971 0.60342142]
[2.79343054 2.93891518 1.20111856]
[14.25251538 14.27335695  5.83170898]
[-38.3539227  -36.25521962 -14.00648308]
[13.29402222 10.52751825  4.96184467]
[-2.91769592 -2.51147621 -0.86155902]
[-1.72920677 -1.33597353 -0.41895627]
[-1.91608779 -1.91020206 -0.39210739]
[3.73359531 4.04211203 1.72108635]
[-4.46780215 -3.8881091  -1.76041966]
[-6.01845357 -5.3287032  -2.48651972]
[11.8876533  10.38370679  4.48263088]
[-2.46156715 -1.89726417 -0.81273223]
[-1.78137015 -1.6501944  -0.46439473]
[-1.46941178 -1.38214955 -0.33031972]
[45.01575352 43.79181967 11.21552785]
[-18.16699112 -17.84264572  -9.04302818]
[-7.83857374 -8.85591121 -3.12